# config.yaml
flask:
  secret_key: ""

cognito:
  authority: ""
  client_id: ""
  client_secret: ""
  metadata_url: ""
  domain: ""
  identity_pool_id: ""
  user_pool_provider_name: ""
  region: "us-east-1"

aws:
  region: "us-east-1"
  access_key: ""
  secret_key: ""
